name: Deploy To Github Pages

on: 
  push:
      branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permission:
      content: read
      pages: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci

      - name: Build Project
        run: npm run build

      - name: Setup Pages
        uses: action/configure-pages@v4

      - name: Upload Artifact
        uses: action/upload-pages-artifact@v3
        with:
          path: './dist'

      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v4
